"""Service-layer helpers for the coordinator API application."""

from coordinator_api.service.agent import AgentAskRequest, AgentRunResult, run_agent_request_summary_merge
from coordinator_api.service.aggregation import (
    AggregationRunNotFoundError,
    NoCompletedParticipantsError,
    aggregate_run_summary_merge,
)
from coordinator_api.service.dispatch import (
    InvalidParticipantExecutionResponseError,
    InvalidParticipantResponseError,
    ParticipantIdentityMismatchError,
    ParticipantExecutionDispatchResult,
    ParticipantExecutionFailedError,
    ParticipantEvaluationFailedError,
    RunNotFoundError,
    TrustedParticipantConfig,
    TrustedParticipantRegistry,
    build_trusted_participant_config,
    build_trusted_participant_registry,
    dispatch_run_to_participant_kb,
    dispatch_run_to_participant_kb_execute,
    dispatch_run_to_participant_logs,
    dispatch_run_to_participant_logs_execute,
    dispatch_run_to_participant_docs,
    dispatch_run_to_participant_docs_execute,
)
from coordinator_api.service.persistence import (
    CoordinatorPersistenceService,
    PersistedEventSummary,
    PersistenceError,
    PersistenceService,
)
from coordinator_api.service.orchestration import (
    NoExecutableParticipantsError,
    OrchestrationResult,
    ParticipantEvaluationRecord,
    ParticipantExecutionRecord,
    ParticipantOrchestrationFailedError,
    orchestrate_run_summary_merge,
)
from coordinator_api.service.state import (
    AggregateResultRecord,
    AggregateSubmissionRecord,
    CompletedParticipant,
    PolicyAttestationRecord,
    RejectedParticipant,
    RunSnapshot,
)
from coordinator_api.service.store import (
    CoordinatorStateError,
    CoordinatorStore,
    DatabaseBackedRunStore,
    InMemoryRunStore,
    RunAlreadyExistsError,
    UnknownRunError,
)

__all__ = [
    "AgentAskRequest",
    "AgentRunResult",
    "CoordinatorStateError",
    "CoordinatorStore",
    "AggregateResultRecord",
    "AggregateSubmissionRecord",
    "aggregate_run_summary_merge",
    "AggregationRunNotFoundError",
    "CompletedParticipant",
    "DatabaseBackedRunStore",
    "CoordinatorPersistenceService",
    "dispatch_run_to_participant_docs",
    "dispatch_run_to_participant_docs_execute",
    "dispatch_run_to_participant_kb",
    "dispatch_run_to_participant_kb_execute",
    "dispatch_run_to_participant_logs",
    "dispatch_run_to_participant_logs_execute",
    "build_trusted_participant_config",
    "build_trusted_participant_registry",
    "InMemoryRunStore",
    "InvalidParticipantExecutionResponseError",
    "InvalidParticipantResponseError",
    "ParticipantIdentityMismatchError",
    "ParticipantExecutionDispatchResult",
    "ParticipantExecutionFailedError",
    "ParticipantEvaluationFailedError",
    "ParticipantEvaluationRecord",
    "ParticipantExecutionRecord",
    "ParticipantOrchestrationFailedError",
    "NoCompletedParticipantsError",
    "NoExecutableParticipantsError",
    "OrchestrationResult",
    "orchestrate_run_summary_merge",
    "PersistedEventSummary",
    "PersistenceError",
    "PersistenceService",
    "PolicyAttestationRecord",
    "RejectedParticipant",
    "RunAlreadyExistsError",
    "RunNotFoundError",
    "RunSnapshot",
    "TrustedParticipantConfig",
    "TrustedParticipantRegistry",
    "UnknownRunError",
    "run_agent_request_summary_merge",
]
